dist: trusty

group: edge

language: java

sudo: required

jdk: openjdk8

cache:
  directories:
    - $HOME/.m2
script:
  - cd Mockup-V2/Backend
  - mvn clean install

notifications:
  slack:
    rooms:
      - sweight:9eGFAhd0BsM6lZ8aNnNjvKED#travis-ci
    on_success: never
