version: "3"
services:
  mongo:
    image: "mongo:3.6"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "./data/db:/data/db"
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null
  app:
    image: doc/colletta-2019
    expose:
      - "8081"
    depends_on:
      - mongo
      - freeling
  mongo-seeding:
    image: pkosiec/mongo-seeding
  freeling:
    build: freelingDocker/.
    ports:
      - "50000:50000"
    entrypoint: analyze -f it.cfg --server -p 50005
