version: '3'
services:
  mongo:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=sweightgroup
      - MONGO_INITDB_ROOT_PASSWORD=sweightgroup2019
    volumes:
      - './data/db:/data/db'
    ports:
      - '27017:27017'
    command: mongod --smallfiles --logpath=/dev/null
  app:
    image: doc/colletta-2019
    expose:
      - '8081'
    depends_on:
      - mongo
  seed:
   build: seedMongo/.
   links: 
    - mongo
  freeling-it:
    image: maga97/freeling
    entrypoint: analyze -f it.cfg --server -p 50001
    ports:
      - '50001:50001'
  freeling-en:
    image: maga97/freeling
    entrypoint: analyze -f en.cfg --server -p 50002
    ports:
      - '50002:50002'
